version: "3.9"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    restart: always
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

    ports:
      - "8123:8123" # HTTP port
      - "9000:9000" # Native port
    volumes:
      - ./db/user_files/:/var/lib/clickhouse/user_files/
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=clickhouse
      - CLICKHOUSE_MAX_MEMORY_USAGE=5000000000

  ch-ui:
    image: ghcr.io/caioricciuti/ch-ui:latest
    container_name: ch-ui
    restart: always
    ports:
      - "5521:5521"
    environment:
      - VITE_CLICKHOUSE_URL=http://127.0.0.1:8123
      - VITE_CLICKHOUSE_USER=default
      - VITE_CLICKHOUSE_PASS=clickhouse
